package org.monogram.domain.models

data class ChatFullInfoModel(
    val description: String? = null,
    val inviteLink: String? = null,
    val memberCount: Int = 0,
    val onlineCount: Int = 0,
    val administratorCount: Int = 0,
    val restrictedCount: Int = 0,
    val bannedCount: Int = 0,
    val birthdate: BirthdateModel? = null,
    val commonGroupsCount: Int = 0,
    val giftCount: Int = 0,
    val isBlocked: Boolean = false,
    val botInfo: String? = null,
    val slowModeDelay: Int = 0,
    val locationAddress: String? = null,
    val canSetStickerSet: Boolean = false,
    val canSetLocation: Boolean = false,
    val canGetMembers: Boolean = false,
    val canGetStatistics: Boolean = false,
    val canGetRevenueStatistics: Boolean = false,
    val linkedChatId: Long = 0L,
    val businessInfo: BusinessInfoModel? = null,
    val note: String? = null,
    val canBeCalled: Boolean = false,
    val supportsVideoCalls: Boolean = false,
    val hasPrivateCalls: Boolean = false,
    val hasPrivateForwards: Boolean = false,
    val hasRestrictedVoiceAndVideoNoteMessages: Boolean = false,
    val hasPostedToProfileStories: Boolean = false,
    val setChatBackground: Boolean = false,
    val incomingPaidMessageStarCount: Long = 0L,
    val outgoingPaidMessageStarCount: Long = 0L,
)